# Pre-commit hooks configuration for ZQ DDC Core V1

repos:
  - repo: local
    hooks:
      - id: manifest-verify
        name: Verify Manifests
        entry: tools/hooks/ddc-verify.sh
        language: script
        files: \.(yaml|yml)$
        always_run: false
        
      - id: check-schema-uri
        name: Check Schema URI
        entry: python3 tools/check_schema_uri.py
        language: system
        files: \.(yaml|yml)$
        pass_filenames: true
        
      - id: validate-schema
        name: Validate Schema
        entry: bash -c 'for f in "$@"; do python3 tools/validate_schema.py "$f" -s schema/manifest.schema.json; done' --
        language: system
        files: \.(yaml|yml)$
        pass_filenames: true
  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']
        files: \.json$
  
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-check
        files: pyproject.toml
        
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        files: \.py$
